# SonarCloud Project Configuration
sonar.projectKey=ericksonlopezf_dotnet-printing
sonar.organization=ericksonlopezf

# Exclusions
sonar.exclusions=samples/**,benchmarks/**,scripts/**,.github/**,**/bin/**,**/obj/**,**/*.js
sonar.coverage.exclusions=tests/**,samples/**,benchmarks/**,docs/**,**/*Tests.cs,**/*Test*.cs,**/tests/**,**/benchmarks/**,**/samples/**,**/bin/**,**/obj/**
sonar.cpd.exclusions=tests/**,**/tests/**,**/*Tests.cs,**/*Test*.cs,**/samples/**,**/benchmarks/**,**/bin/**,**/obj/**,**/*MonochromeBitmapConverter.cs
